package org.protege.notesapi.oc;

import org.protege.notesapi.NotesConstants;
import org.protege.notesapi.oc.impl.*;
import org.protege.notesapi.util.OntologyJavaMappingUtil;

/**
 * Generated by Protege (http://protege.stanford.edu).
 *
 * @version generated on Mon Aug 18 21:11:09 GMT-08:00 2008
 */
/** @author csnyulas */
public class OntologyJavaMapping {

    public static final String NAMESPACE = NotesConstants.CHAO_NAMESPACE;

    public static void initMap() {
        OntologyJavaMappingUtil.add(NAMESPACE + "Ontology_Component" ,
                                    OntologyComponent.class,
                                    DefaultOntologyComponent.class);
        OntologyJavaMappingUtil.add(NAMESPACE + "Ontology_Class" , OntologyClass.class, DefaultOntologyClass.class);
        OntologyJavaMappingUtil.add(NAMESPACE + "Ontology_Property" ,
                                    OntologyProperty.class,
                                    DefaultOntologyProperty.class);
        OntologyJavaMappingUtil.add(NAMESPACE + "Ontology_Individual" ,
                                    OntologyIndividual.class,
                                    DefaultOntologyIndividual.class);
        OntologyJavaMappingUtil.add(NAMESPACE + "Ontology" , Ontology.class, DefaultOntology.class);
    }
}
